### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by fif911** [zoeycui94/Global-conflict-prediction-python#1]
Hey. 
Great work. I am also interested in conflict prediction and decided to do my thesis on this topic also. I found a couple of issues but still wanted to say thank you for your work and for publishing it. If you are still interested in working further on this topic we can collaborate and maybe push it to some publication. I am working now on https://viewsforecasting.org/prediction-competition-2/ to try to estimate not wars but fatalities as that would be regression and not 1:0 classification and allow for a smaller imbalance.

Let me know if you are interested :)
Best, Oleksandr

**Comment by zoeycui94** [comment]
Hey Oleksandr,

Thank you for reaching out!  I’m glad to hear you are exploring this area too, especially with a focus on fatalities, which certainly adds depth beyond binary classifications. 

Your project sounds fascinating, and I am indeed interested in discussing how we might advance this work together. Can you tell me more about it and how far you have worked on this project?

Best,
Zoey

**Comment by fif911** [comment]
Hey Zoey

I am glad you liked the idea. I have to admit that GitHub Issues is not the best messenger. Let's connect on LinkedIn (or anywhere else) and I will tell you the details :) 

This is mine: https://www.linkedin.com/in/alex-zakotianskiy/

Best regards, Oleksandr
